In [1]:
import os
import pandas as pd
import fitz ##PyMuPDF
import glob
import copy

In [2]:
pdf_dir = '../pdf/*.pdf'

In [3]:
g = glob.glob( pdf_dir )
len(g),g[:3]

(38,
 ['../pdf\\CWC2018-19_Leg1_ResultsBook.pdf',
  '../pdf\\CWC2018-19_Leg2_ResultsBook.pdf',
  '../pdf\\CWC2018-19_Leg3_ResultsBook.pdf'])

In [4]:
fn = g[0]
fn

'../pdf\\CWC2018-19_Leg1_ResultsBook.pdf'

In [9]:
doc = fitz.open(fn)

In [16]:
def keyPosion( test_array , key ):
    if not key in test_array: return -1
    else: return test_array.index(key)

In [17]:
page = 19
text = doc[page].get_text()
q = text.split('\n')

key = 'Game Results'  
title_index = keyPosion( q , key )
if title_index < 0 :pass
else:
    print(f'index{title_index}')
    display(q[title_index:])

index7

['Game Results',
 'Group-B - Sheet B',
 'Sheet',
 'Team',
 'LSFE',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 'Total',
 'Points',
 'Game',
 '6',
 ' 8',
 'CAN - Canada (Homan)',
 '1',
 '0',
 '0',
 '2',
 '2',
 '2',
 '1',
 'X',
 '*',
 '3',
 '6',
 ' 2',
 'USA - United States (Roth)',
 '0',
 '0',
 '2',
 '0',
 '0',
 '0',
 '0',
 'X',
 '0',
 'CAN - Canada',
 '   Game',
 'Shot Success',
 'USA - United States',
 '   Game',
 'Shot Success',
 '4 S',
 'HOMAN Rachel',
 ' 84%',
 '4 S',
 'ROTH Nina',
 ' 61%',
 '3 V',
 'MISKEW Emma',
 ' 88%',
 '3 V',
 'PETERSON Tabitha',
 ' 64%',
 '2',
 'COURTNEY Joanne',
 ' 80%',
 '2',
 'HAMILTON Becca',
 ' 68%',
 '1',
 'WEAGLE Lisa',
 ' 79%',
 '1',
 'GEVING Aileen',
 ' 64%',
 'A',
 '-',
 '-',
 'A',
 '-',
 '-',
 'Team Total',
 ' 83%',
 'Team Total',
 ' 64%',
 'Shot Success Analysis',
 'CAN - Canada',
 'Game',
 'USA - United States',
 'Game',
 '4 HOMAN Rachel',
 ' 84',
 '5  85',
 '9  83',
 '14',
 'Total',
 '2',
 '4',
 '3',
 '5',
 ' 88',
 ' 88',
 ' 83',
 ' 80',
 '6',
 '8',
 ' 88',
 ' 81',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 'Draws',
 'Take-outs',
 '4 ROTH Nina',
 ' 61',
 '7  50',
 '7  71',
 '14',
 'Total',
 '2',
 '4',
 '5',
 '3',
 ' 13',
 ' 63',
 ' 65',
 ' 83',
 '6',
 '8',
 ' 46',
 ' 72',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 'Draws',
 'Take-outs',
 '3 MISKEW Emma',
 ' 88',
 '5  90',
 '9  86',
 '14',
 'Total',
 '1',
 '6',
 '4',
 '3',
 '100',
 ' 92',
 ' 88',
 ' 75',
 '7',
 '7',
 ' 93',
 ' 82',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 'Draws',
 'Take-outs',
 '3 PETERSON Tabitha',
 ' 64',
 '5  85',
 '9  53',
 '14',
 'Total',
 '0',
 '5',
 '5',
 '4',
 ' 40',
 ' 85',
 ' 69',
 '5',
 '9',
 ' 40',
 ' 78',
 '-',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 'Draws',
 'Take-outs',
 '2 COURTNEY Joanne',
 ' 80',
 '7  75',
 '7  86',
 '14',
 'Total',
 '2',
 '5',
 '5',
 '2',
 ' 63',
 ' 90',
 ' 80',
 ' 75',
 '7',
 '7',
 ' 82',
 ' 79',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 'Draws',
 'Take-outs',
 '2 HAMILTON Becca',
 ' 68',
 '7  64',
 '7  71',
 '14',
 'Total',
 '5',
 '5',
 '2',
 '2',
 ' 65',
 ' 65',
 ' 63',
 ' 88',
 '10',
 '4',
 ' 65',
 ' 75',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 'Draws',
 'Take-outs',
 '1 WEAGLE Lisa',
 ' 79',
 '14  79',
 '0',
 '14',
 'Total',
 '5',
 '0',
 '9',
 '0',
 ' 80',
 ' 78',
 '5',
 '9',
 ' 80',
 ' 78',
 '%',
 '%',
 '%',
 '-',
 '-',
 '-',
 '%',
 '%',
 '%',
 'Draws',
 'Take-outs',
 '1 GEVING Aileen',
 ' 64',
 '12  73',
 '2  13',
 '14',
 'Total',
 '6',
 '1',
 '6',
 '1',
 ' 79',
 '  0',
 ' 67',
 ' 25',
 '7',
 '7',
 ' 68',
 ' 61',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 'Draws',
 'Take-outs',
 'A -',
 '0',
 '0',
 '0',
 'Total',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 'Draws',
 'Take-outs',
 'A -',
 '0',
 '0',
 '0',
 'Total',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 'Draws',
 'Take-outs',
 ' 83',
 '31  81',
 '25  85',
 '56',
 'Team',
 'Total',
 '10  80',
 '15  90',
 '21  81',
 '10  78',
 '31',
 '25  86',
 ' 80',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 'Draws',
 'Take-outs',
 ' 64',
 '31  68',
 '25  60',
 '56',
 'Team',
 'Total',
 '13  63',
 '15  52',
 '18  71',
 '10  73',
 '28',
 '28  57',
 ' 71',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 '%',
 'Draws',
 'Take-outs',
 'Note:',
 'Position and function for each team member:',
 '4 = Fourth, 3 = Third, 2 = Second, 1 = Lead, A = Alternate, S = Skip, V = Vice-Skip ',
 'Legend:',
 'Clockwise',
 'Counter-clockwise',
 'LSFE(*) Last Stone First End',
 'Unplayed/unfinished end due to concession',
 'X',
 'CURWTEAM4-------------GPB-001501--_73 1.0',
 'Report Created  SAT 15 SEP 2018 21:18',
 'Page 1/1',
 '']

In [18]:
page = 330
text = doc[page].get_text()
q = text.split('\n')

key0 = 'Game Results'
title_index = keyPosion( q , key0 )
if title_index < 0 :pass
else:
    contents = q[title_index:]
    print(f'index{title_index}')
    display(q[title_index:title_index+45])

index7

['Game Results',
 'Group-A - Sheet A',
 'Sheet',
 'Team',
 'LSFE',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 'Total',
 'SO',
 'Points',
 'Game',
 '4',
 ' 8',
 'USA - United States (Ruohonen)',
 '2',
 '0',
 '2',
 '0',
 '2',
 '0',
 '0',
 '2',
 '0',
 '*',
 '1',
 '4',
 ' 9',
 'SWE - Sweden (Edin)',
 '0',
 '3',
 '0',
 '2',
 '0',
 '2',
 '1',
 '0',
 '1',
 '2',
 'USA - United States']

In [19]:
key_1 = "Team" ; key_2 = "Game"
score_head_1 = keyPosion( contents , key_1 )
score_head_2 = keyPosion( contents , key_2 )
contents_body = contents[score_head_2:]
score_head_1 , score_head_2

(3, 16)

In [20]:
l_head = contents[score_head_1:score_head_2+1]
l_head , len(l_head)

(['Team',
  'LSFE',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  'Total',
  'SO',
  'Points',
  'Game'],
 14)

In [21]:
a = 0+1; b = a + len(l_head)
t1 = contents_body[a:b]
t1 ,len(t1)

(['4',
  ' 8',
  'USA - United States (Ruohonen)',
  '2',
  '0',
  '2',
  '0',
  '2',
  '0',
  '0',
  '2',
  '0',
  '*',
  '1'],
 14)

In [22]:
a2 = b; b2 = a2 + len(l_head)
t2= contents_body[a2:b2]
t2 ,len(t2)

(['4',
  ' 9',
  'SWE - Sweden (Edin)',
  '0',
  '3',
  '0',
  '2',
  '0',
  '2',
  '1',
  '0',
  '1',
  '2',
  'USA - United States'],
 14)

In [23]:
pd.DataFrame([t1,t2],columns=l_head)

,Team,LSFE,1,2,3,4,5,6,7,8,Total,SO,Points,Game
0,4,8,USA - United States (Ruohonen),2,0,2,0,2,0,0,2,0,*,1
1,4,9,SWE - Sweden (Edin),0,3,0,2,0,2,1,0,1,2,USA - United States

In [24]:
lm = [l_head[-1]]+l_head[0:-1]
pd.DataFrame([t1,t2],columns=lm)

,Game,Team,LSFE,1,2,3,4,5,6,7,8,Total,SO,Points
0,4,8,USA - United States (Ruohonen),2,0,2,0,2,0,0,2,0,*,1
1,4,9,SWE - Sweden (Edin),0,3,0,2,0,2,1,0,1,2,USA - United States

In [25]:
def score_convert(base_texts):
    t = copy.deepcopy(base_texts) 
    if False == t[-1].isdecimal():
        t[-1] = t[-2]
        t[-2] = ""
    #2個目を最後から２つ目と入れ替えます
    v_pos_head2 = t[1]
    v_pos_tail2 = t[-2]
    t[-2] = v_pos_head2
    t[1] = v_pos_tail2
    #2個目と3個目を入れ替えます
    v_pos_head2 = t[1]
    v_pos_head3= t[2]
    t[2] = v_pos_head2
    t[1] = v_pos_head3
    return t
t1b = score_convert(t1)
t2b = score_convert(t2)
df = pd.DataFrame([t1b,t2b],columns=lm)
df

,Game,Team,LSFE,1,2,3,4,5,6,7,8,Total,SO,Points
0,4,USA - United States (Ruohonen),*,2,0,2,0,2,0,0,2,0,8,1
1,4,SWE - Sweden (Edin),,0,3,0,2,0,2,1,0,1,9,2

In [33]:
if 'SO' in df.columns:
    so_v = df['SO'].to_list()
    total_v = df['Total'].to_list()
    df['SO'] = total_v
    df['Total'] = so_v
    columns = df.columns.to_list()
    so_index = columns.index('SO')
    total_index = columns.index('Total')
    total_v = columns.pop(total_index)
    columns.insert(so_index,total_v)
    df.columns = columns

In [34]:
df

,Game,Team,LSFE,1,2,3,4,5,6,7,8,SO,Total,Points
0,4,USA - United States (Ruohonen),*,2,0,2,0,2,0,0,2,0,8,1
1,4,SWE - Sweden (Edin),,0,3,0,2,0,2,1,0,1,9,2

In [64]:
def keyPosion( test_array , key ):
    print(test_array)
    if not key in test_array: return -1
    else: return test_array.index(key)

In [69]:
def GetScorePosision( contents ):
    key_1 = "Team" ; key_2 = "Points"
    score_head_1 = keyPosion( contents , key_1 )
    score_head_2 = keyPosion( contents , key_2 )
    contents_body = contents[score_head_2:]
    return score_head_1 , score_head_2 + 1

In [70]:
def score_convert(base_texts):
    t = copy.deepcopy(base_texts) 
    if False == t[-1].isdecimal():
        t[-1] = t[-2]
        t[-2] = ""
    #2個目を最後から２つ目と入れ替えます
    v_pos_head2 = t[1]
    v_pos_tail2 = t[-2]
    t[-2] = v_pos_head2
    t[1] = v_pos_tail2
    #2個目と3個目を入れ替えます
    v_pos_head2 = t[1]
    v_pos_head3= t[2]
    t[2] = v_pos_head2
    t[1] = v_pos_head3
    return t
    
def ScoreSolve( contents , score_head_1 , score_head_2 ):
    l_head = contents[score_head_1:score_head_2+1]
    print( l_head , len(l_head) )
    lm = [l_head[-1]]+l_head[0:-1]

    a = 0+1; b = a + len(l_head)
    t1 = contents_body[a:b]
    t1 ,len(t1)

    a2 = b; b2 = a2 + len(l_head)
    t2= contents_body[a2:b2]
    t2 ,len(t2)

    tc1 = score_convert(t1)
    tc2 = score_convert(t2)

    df = pd.DataFrame([t1b,t2b],columns=lm)
    return df

In [72]:
dest_list = []

for i ,page in enumerate(doc):   
    if i < 5 : continue
    text = page.get_text()
    key = 'Game Results'  
    title_index = keyPosion( text, key )
    if title_index < 0 :
        #print('pass')
        pass
    else:
        q = text[title_index:]
        print(f'page{i}:index->{title_index}')
        print( keyPosion(q ,'Game' ) , q[0] , q[1],)
        pos1 , pos2 = GetScorePosision( q )
        if pos1 <= 0 or pos2 <= 0:
            print( f'pass:{i}',pos1,pos2)
        else:
            assert( pos1 > 0 )
            assert( pos2 > 0 )
            contents_body = contents[score_head_2:]
            df = ScoreSolve( contents_body , pos1 ,pos2 )
        
            if 'SO' in df.columns:
                so_v = df['SO'].to_list()
                total_v = df['Total'].to_list()
                df['SO'] = total_v
                df['Total'] = so_v
                columns = df.columns.to_list()
                so_index = columns.index('SO')
                total_index = columns.index('Total')
                total_v = columns.pop(total_index)
                columns.insert(so_index,total_v)
                df.columns = columns
            dest_list.append(df)
 
    pass
print('fin',len(dest_list))

Start Time 12:00
SUN 16 SEP 2018
Curling World Cup 2018-19 Leg 1
Women
Final
Suzhou, China
Suzhou Olympic Sports Centre
Session Results and Standings
Sheet
Team
LSFE
1
2
3
4
5
6
7
8
Total
Points
 7
CAN - Canada (Homan)
0
2
1
0
1
0
0
3
*
10
 3
SWE - Sweden (Hasselborg)
0
0
0
1
0
2
0
0
5
Final Standings
Team
Rank
Points
Gold
CAN - Canada
25
  2
SWE - Sweden
20
  3
RUS - Russia
9
  4
JPN - Japan
9
  5
USA - United States
9
  6
SCO - Scotland
6
  7
CHN - China
6
  8
KOR - Korea
3
Legend:
Last Stone First End
LSFE(*)
CURWTEAM4-------------FNL-000100--_74B 1.0
Report Created  SUN 16 SEP 2018 14:03
Page 1/1

Start Time 12:00
SUN 16 SEP 2018
Curling World Cup 2018-19 Leg 1
Women
Final
Suzhou, China
Suzhou Olympic Sports Centre
Game Results
Sheet
Team
LSFE
1
2
3
4
5
6
7
8
Total
Points
Game
7
 7
CAN - Canada (Homan)
0
2
1
0
1
0
0
3
*
10
7
 3
SWE - Sweden (Hasselborg)
0
0
0
1
0
2
0
0
5
CAN - Canada
   Game
Shot Success
SWE - Sweden
   Game
Shot Success
4 S
HOMAN Rachel
 83%
4 S
HASSELBORG Anna
 67%
3 V
MISKEW Emma
 94%
3 V
McMANUS Sara
 86%
2
COURTNEY Joanne
 86%
2
KNOCHENHAUER Agnes
 89%
1
WEAGLE Lisa
 69%
1
MABERGS Sofia
 73%
A
-
-
A
-
-
Team Total
 83%
Team Total
 79%
Shot Success Analysis
CAN - Canada
Game
SWE - Sweden
Game
4 HOMAN Rachel
 83
4  69
12  88
16
Total
1
7
3
5
 50
 86
 75
 90
8
8
 81
 84
%
%
%
%
%
%
%
%
%
Draws
Take-outs
4 HASSELBORG Anna
 67
8  72
8  63
16
Total
2
3
6
5
 63
 83
 75
 50
5
11
 75
 64
%
%
%
%
%
%
%
%
%
Draws
Take-outs
3 MISKEW Emma
 94
3 100
13  92
16
Total
1
7
2
6
100
100
100
 83
8
8
100
 88
%
%
%
%
%
%
%
%
%
Draws
Take-outs
3 McMANUS Sara
 86
11  86
5  85
16
Total
0
1
11
4
100
 86
 81
1
15
100
 85
-
%
%
%
%
%
%
%
%
Draws
Take-outs
2 COURTNEY Joanne
 86
5  85
11  86
16
Total
0
8
5
3
 88
 85
 83
8
8
 88
 84
-
%
%
%
%
%
%
%
%
Draws
Take-outs
2 KNOCHENHAUER
Agnes
 89
10  95
6  79
16
Total
2
1
8
5
 88
100
 97
 75
3
13
 92
 88
%
%
%
%
%
%
%
%
%
Draws
Take-outs
1 WEAGLE Lisa
 69
12  60
4  94
16
Total
4
1
8
3
 75
100
 53
 92
5
11
 80
 64
%
%
%
%
%
%
%
%
%
Draws
Take-outs
1 MABERGS Sofia
 73
16  73
0
16
Total
8
0
8
0
 88
 59
8
8
 88
 59
%
%
%
-
-
-
%
%
%
Draws
Take-outs
A -
0
0
0
Total
0
0
0
0
0
0
-
-
-
-
-
-
-
-
-
Draws
Take-outs
A -
0
0
0
Total
0
0
0
0
0
0
-
-
-
-
-
-
-
-
-
Draws
Take-outs
 83
24  72
40  89
64
Team
Total
6  75
23  91
18  71
17  87
35
29  88
 79
%
%
%
%
%
%
%
%
%
Draws
Take-outs
 79
45  81
19  74
64
Team
Total
12  83
5  90
33  80
14  68
47
17  85
 77
%
%
%
%
%
%
%
%
%
Draws
Take-outs
Note:
Position and function for each team member:
4 = Fourth, 3 = Third, 2 = Second, 1 = Lead, A = Alternate, S = Skip, V = Vice-Skip
Legend:
Clockwise
Counter-clockwise
Last Stone First End
LSFE(*)
CURWTEAM4-------------FNL-000101--_73 1.0
Report Created  SUN 16 SEP 2018 14:04
Page 1/1

page6:index->120
Game Results
Sheet
Team
LSFE
1
2
3
4
5
6
7
8
Total
Points
Game
7
 7
CAN - Canada (Homan)
0
2
1
0
1
0
0
3
*
10
7
 3
SWE - Sweden (Hasselborg)
0
0
0
1
0
2
0
0
5
CAN - Canada
   Game
Shot Success
SWE - Sweden
   Game
Shot Success
4 S
HOMAN Rachel
 83%
4 S
HASSELBORG Anna
 67%
3 V
MISKEW Emma
 94%
3 V
McMANUS Sara
 86%
2
COURTNEY Joanne
 86%
2
KNOCHENHAUER Agnes
 89%
1
WEAGLE Lisa
 69%
1
MABERGS Sofia
 73%
A
-
-
A
-
-
Team Total
 83%
Team Total
 79%
Shot Success Analysis
CAN - Canada
Game
SWE - Sweden
Game
4 HOMAN Rachel
 83
4  69
12  88
16
Total
1
7
3
5
 50
 86
 75
 90
8
8
 81
 84
%
%
%
%
%
%
%
%
%
Draws
Take-outs
4 HASSELBORG Anna
 67
8  72
8  63
16
Total
2
3
6
5
 63
 83
 75
 50
5
11
 75
 64
%
%
%
%
%
%
%
%
%
Draws
Take-outs
3 MISKEW Emma
 94
3 100
13  92
16
Total
1
7
2
6
100
100
100
 83
8
8
100
 88
%
%
%
%
%
%
%
%
%
Draws
Take-outs
3 McMANUS Sara
 86
11  86
5  85
16
Total
0
1
11
4
100
 86
 81
1
15
100
 85
-
%
%
%
%
%
%
%
%
Draws
Take-outs
2 COURTNEY Joanne
 86
5  85
11  86
16
Total
0
8
5
3
 88
 85
 83
8
8
 88
 84
-
%
%
%
%
%
%
%
%
Draws
Take-outs
2 KNOCHENHAUER
Agnes
 89
10  95
6  79
16
Total
2
1
8
5
 88
100
 97
 75
3
13
 92
 88
%
%
%
%
%
%
%
%
%
Draws
Take-outs
1 WEAGLE Lisa
 69
12  60
4  94
16
Total
4
1
8
3
 75
100
 53
 92
5
11
 80
 64
%
%
%
%
%
%
%
%
%
Draws
Take-outs
1 MABERGS Sofia
 73
16  73
0
16
Total
8
0
8
0
 88
 59
8
8
 88
 59
%
%
%
-
-
-
%
%
%
Draws
Take-outs
A -
0
0
0
Total
0
0
0
0
0
0
-
-
-
-
-
-
-
-
-
Draws
Take-outs
A -
0
0
0
Total
0
0
0
0
0
0
-
-
-
-
-
-
-
-
-
Draws
Take-outs
 83
24  72
40  89
64
Team
Total
6  75
23  91
18  71
17  87
35
29  88
 79
%
%
%
%
%
%
%
%
%
Draws
Take-outs
 79
45  81
19  74
64
Team
Total
12  83
5  90
33  80
14  68
47
17  85
 77
%
%
%
%
%
%
%
%
%
Draws
Take-outs
Note:
Position and function for each team member:
4 = Fourth, 3 = Third, 2 = Second, 1 = Lead, A = Alternate, S = Skip, V = Vice-Skip
Legend:
Clockwise
Counter-clockwise
Last Stone First End
LSFE(*)
CURWTEAM4-------------FNL-000101--_73 1.0
Report Created  SUN 16 SEP 2018 14:04
Page 1/1

0 G a
Game Results
Sheet
Team
LSFE
1
2
3
4
5
6
7
8
Total
Points
Game
7
 7
CAN - Canada (Homan)
0
2
1
0
1
0
0
3
*
10
7
 3
SWE - Sweden (Hasselborg)
0
0
0
1
0
2
0
0
5
CAN - Canada
   Game
Shot Success
SWE - Sweden
   Game
Shot Success
4 S
HOMAN Rachel
 83%
4 S
HASSELBORG Anna
 67%
3 V
MISKEW Emma
 94%
3 V
McMANUS Sara
 86%
2
COURTNEY Joanne
 86%
2
KNOCHENHAUER Agnes
 89%
1
WEAGLE Lisa
 69%
1
MABERGS Sofia
 73%
A
-
-
A
-
-
Team Total
 83%
Team Total
 79%
Shot Success Analysis
CAN - Canada
Game
SWE - Sweden
Game
4 HOMAN Rachel
 83
4  69
12  88
16
Total
1
7
3
5
 50
 86
 75
 90
8
8
 81
 84
%
%
%
%
%
%
%
%
%
Draws
Take-outs
4 HASSELBORG Anna
 67
8  72
8  63
16
Total
2
3
6
5
 63
 83
 75
 50
5
11
 75
 64
%
%
%
%
%
%
%
%
%
Draws
Take-outs
3 MISKEW Emma
 94
3 100
13  92
16
Total
1
7
2
6
100
100
100
 83
8
8
100
 88
%
%
%
%
%
%
%
%
%
Draws
Take-outs
3 McMANUS Sara
 86
11  86
5  85
16
Total
0
1
11
4
100
 86
 81
1
15
100
 85
-
%
%
%
%
%
%
%
%
Draws
Take-outs
2 COURTNEY Joanne
 86
5  85
11  86
16
Total
0
8
5
3
 88
 85
 83
8
8
 88
 84
-
%
%
%
%
%
%
%
%
Draws
Take-outs
2 KNOCHENHAUER
Agnes
 89
10  95
6  79
16
Total
2
1
8
5
 88
100
 97
 75
3
13
 92
 88
%
%
%
%
%
%
%
%
%
Draws
Take-outs
1 WEAGLE Lisa
 69
12  60
4  94
16
Total
4
1
8
3
 75
100
 53
 92
5
11
 80
 64
%
%
%
%
%
%
%
%
%
Draws
Take-outs
1 MABERGS Sofia
 73
16  73
0
16
Total
8
0
8
0
 88
 59
8
8
 88
 59
%
%
%
-
-
-
%
%
%
Draws
Take-outs
A -
0
0
0
Total
0
0
0
0
0
0
-
-
-
-
-
-
-
-
-
Draws
Take-outs
A -
0
0
0
Total
0
0
0
0
0
0
-
-
-
-
-
-
-
-
-
Draws
Take-outs
 83
24  72
40  89
64
Team
Total
6  75
23  91
18  71
17  87
35
29  88
 79
%
%
%
%
%
%
%
%
%
Draws
Take-outs
 79
45  81
19  74
64
Team
Total
12  83
5  90
33  80
14  68
47
17  85
 77
%
%
%
%
%
%
%
%
%
Draws
Take-outs
Note:
Position and function for each team member:
4 = Fourth, 3 = Third, 2 = Second, 1 = Lead, A = Alternate, S = Skip, V = Vice-Skip
Legend:
Clockwise
Counter-clockwise
Last Stone First End
LSFE(*)
CURWTEAM4-------------FNL-000101--_73 1.0
Report Created  SUN 16 SEP 2018 14:04
Page 1/1

Game Results
Sheet
Team
LSFE
1
2
3
4
5
6
7
8
Total
Points
Game
7
 7
CAN - Canada (Homan)
0
2
1
0
1
0
0
3
*
10
7
 3
SWE - Sweden (Hasselborg)
0
0
0
1
0
2
0
0
5
CAN - Canada
   Game
Shot Success
SWE - Sweden
   Game
Shot Success
4 S
HOMAN Rachel
 83%
4 S
HASSELBORG Anna
 67%
3 V
MISKEW Emma
 94%
3 V
McMANUS Sara
 86%
2
COURTNEY Joanne
 86%
2
KNOCHENHAUER Agnes
 89%
1
WEAGLE Lisa
 69%
1
MABERGS Sofia
 73%
A
-
-
A
-
-
Team Total
 83%
Team Total
 79%
Shot Success Analysis
CAN - Canada
Game
SWE - Sweden
Game
4 HOMAN Rachel
 83
4  69
12  88
16
Total
1
7
3
5
 50
 86
 75
 90
8
8
 81
 84
%
%
%
%
%
%
%
%
%
Draws
Take-outs
4 HASSELBORG Anna
 67
8  72
8  63
16
Total
2
3
6
5
 63
 83
 75
 50
5
11
 75
 64
%
%
%
%
%
%
%
%
%
Draws
Take-outs
3 MISKEW Emma
 94
3 100
13  92
16
Total
1
7
2
6
100
100
100
 83
8
8
100
 88
%
%
%
%
%
%
%
%
%
Draws
Take-outs
3 McMANUS Sara
 86
11  86
5  85
16
Total
0
1
11
4
100
 86
 81
1
15
100
 85
-
%
%
%
%
%
%
%
%
Draws
Take-outs
2 COURTNEY Joanne
 86
5  85
11  86
16
Total
0
8
5
3
 88
 85
 83
8
8
 88
 84
-
%
%
%
%
%
%
%
%
Draws
Take-outs
2 KNOCHENHAUER
Agnes
 89
10  95
6  79
16
Total
2
1
8
5
 88
100
 97
 75
3
13
 92
 88
%
%
%
%
%
%
%
%
%
Draws
Take-outs
1 WEAGLE Lisa
 69
12  60
4  94
16
Total
4
1
8
3
 75
100
 53
 92
5
11
 80
 64
%
%
%
%
%
%
%
%
%
Draws
Take-outs
1 MABERGS Sofia
 73
16  73
0
16
Total
8
0
8
0
 88
 59
8
8
 88
 59
%
%
%
-
-
-
%
%
%
Draws
Take-outs
A -
0
0
0
Total
0
0
0
0
0
0
-
-
-
-
-
-
-
-
-
Draws
Take-outs
A -
0
0
0
Total
0
0
0
0
0
0
-
-
-
-
-
-
-
-
-
Draws
Take-outs
 83
24  72
40  89
64
Team
Total
6  75
23  91
18  71
17  87
35
29  88
 79
%
%
%
%
%
%
%
%
%
Draws
Take-outs
 79
45  81
19  74
64
Team
Total
12  83
5  90
33  80
14  68
47
17  85
 77
%
%
%
%
%
%
%
%
%
Draws
Take-outs
Note:
Position and function for each team member:
4 = Fourth, 3 = Third, 2 = Second, 1 = Lead, A = Alternate, S = Skip, V = Vice-Skip
Legend:
Clockwise
Counter-clockwise
Last Stone First End
LSFE(*)
CURWTEAM4-------------FNL-000101--_73 1.0
Report Created  SUN 16 SEP 2018 14:04
Page 1/1

['3', '0', '2', '0', '2', '1', '0', '1', '2', 'USA - United States', 'SWE - Sweden', '4 V', 'PERSINGER Greg', '4 S', 'EDIN Niklas', '3 S', 'RUOHONEN Rich', '3 V', 'ERIKSSON Oskar', '2', 'BEIGHTON Sean', '2', 'WRANAA Rasmus', '1', 'NERNBERGER Kroy', '1', 'SUNDGREN Christoffer', 'A', '-', 'A', '-', 'Shoot-out: 199.6cm (PERSINGER G)', 'Shoot-out: 44.1cm (SUNDGREN C)', 'Note:'] 34

ValueError: 34 columns passed, passed data had 14 columns

In [47]:
page = 6
text = doc[page].get_text()
text

'Start Time 12:00\nSUN 16 SEP 2018\nCurling World Cup 2018-19 Leg 1\nWomen\nFinal\nSuzhou, China\nSuzhou Olympic Sports Centre\nGame Results\nSheet\nTeam\nLSFE\n1\n2\n3\n4\n5\n6\n7\n8\nTotal\nPoints\nGame\n7\n 7\nCAN - Canada (Homan)\n0\n2\n1\n0\n1\n0\n0\n3\n*\n10\n7\n 3\nSWE - Sweden (Hasselborg)\n0\n0\n0\n1\n0\n2\n0\n0\n5\nCAN - Canada\n   Game\nShot Success\nSWE - Sweden\n   Game\nShot Success\n4 S\nHOMAN Rachel\n 83%\n4 S\nHASSELBORG Anna\n 67%\n3 V\nMISKEW Emma\n 94%\n3 V\nMcMANUS Sara\n 86%\n2\nCOURTNEY Joanne\n 86%\n2\nKNOCHENHAUER Agnes\n 89%\n1\nWEAGLE Lisa\n 69%\n1\nMABERGS Sofia\n 73%\nA\n-\n-\nA\n-\n-\nTeam Total\n 83%\nTeam Total\n 79%\nShot Success Analysis\nCAN - Canada\nGame\nSWE - Sweden\nGame\n4 HOMAN Rachel\n 83\n4  69\n12  88\n16\nTotal\n1\n7\n3\n5\n 50\n 86\n 75\n 90\n8\n8\n 81\n 84\n%\n%\n%\n%\n%\n%\n%\n%\n%\nDraws\nTake-outs\n4 HASSELBORG Anna\n 67\n8  72\n8  63\n16\nTotal\n2\n3\n6\n5\n 63\n 83\n 75\n 50\n5\n11\n 75\n 64\n%\n%\n%\n%\n%\n%\n%\n%\n%\nDraws\nTake-outs\n3 MISKEW Emma\n 94\n3 100\n13  92\n16\nTotal\n1\n7\n2\n6\n100\n100\n100\n 83\n8\n8\n100\n 88\n%\n%\n%\n%\n%\n%\n%\n%\n%\nDraws\nTake-outs\n3 McMANUS Sara\n 86\n11  86\n5  85\n16\nTotal\n0\n1\n11\n4\n100\n 86\n 81\n1\n15\n100\n 85\n-\n%\n%\n%\n%\n%\n%\n%\n%\nDraws\nTake-outs\n2 COURTNEY Joanne\n 86\n5  85\n11  86\n16\nTotal\n0\n8\n5\n3\n 88\n 85\n 83\n8\n8\n 88\n 84\n-\n%\n%\n%\n%\n%\n%\n%\n%\nDraws\nTake-outs\n2 KNOCHENHAUER \nAgnes\n 89\n10  95\n6  79\n16\nTotal\n2\n1\n8\n5\n 88\n100\n 97\n 75\n3\n13\n 92\n 88\n%\n%\n%\n%\n%\n%\n%\n%\n%\nDraws\nTake-outs\n1 WEAGLE Lisa\n 69\n12  60\n4  94\n16\nTotal\n4\n1\n8\n3\n 75\n100\n 53\n 92\n5\n11\n 80\n 64\n%\n%\n%\n%\n%\n%\n%\n%\n%\nDraws\nTake-outs\n1 MABERGS Sofia\n 73\n16  73\n0\n16\nTotal\n8\n0\n8\n0\n 88\n 59\n8\n8\n 88\n 59\n%\n%\n%\n-\n-\n-\n%\n%\n%\nDraws\nTake-outs\nA -\n0\n0\n0\nTotal\n0\n0\n0\n0\n0\n0\n-\n-\n-\n-\n-\n-\n-\n-\n-\nDraws\nTake-outs\nA -\n0\n0\n0\nTotal\n0\n0\n0\n0\n0\n0\n-\n-\n-\n-\n-\n-\n-\n-\n-\nDraws\nTake-outs\n 83\n24  72\n40  89\n64\nTeam\nTotal\n6  75\n23  91\n18  71\n17  87\n35\n29  88\n 79\n%\n%\n%\n%\n%\n%\n%\n%\n%\nDraws\nTake-outs\n 79\n45  81\n19  74\n64\nTeam\nTotal\n12  83\n5  90\n33  80\n14  68\n47\n17  85\n 77\n%\n%\n%\n%\n%\n%\n%\n%\n%\nDraws\nTake-outs\nNote:\nPosition and function for each team member:\n4 = Fourth, 3 = Third, 2 = Second, 1 = Lead, A = Alternate, S = Skip, V = Vice-Skip \nLegend:\nClockwise\nCounter-clockwise\nLast Stone First End\nLSFE(*)\nCURWTEAM4-------------FNL-000101--_73 1.0\nReport Created  SUN 16 SEP 2018 14:04\nPage 1/1\n'

In [48]:
 key = 'Game Results'  
 keyPosion( text, key )

120